#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source /opt/resource/common.sh

# Read inputs
source=$1
payload=$(mktemp kubectl-resource-request.XXXXXX)
cat > $payload <&0

# Prepare
setup_resource $payload $source
echo "Resource setup successful."

# Parse parameters
configuration=$(jq -r '.params.configuration // ""' < $payload)
delete=$(jq -r '.params.delete // "false"' < $payload)

istioctl_create() {
  echo "Creating the configuration $configuration..."
  config_args=("-f" "$source/$configuration")
  logfile="/tmp/log"
  mkdir -p /tmp
  create_args=("create ${config_args[@]} | tee $logfile")
  echo "Running command istioctl ${create_args[@]}"
  create_error=$(("istioctl ${create_args[@]}") 2>&1)

  if [[ $create_error =~ ^Error:( ).+( )already( )exists$ ]]; then
    echo "Create with $configuration failed because resource already exists"
    replace_args=("replace ${config_args[@]} | tee $logfile")
    echo "Running command istioctl ${replace_args}"
    replace_result=$("istioctl ${replace_args[@]}")
  fi
}

istioctl_delete() {
  if [ -z "$configuration" ]; then
    echo "invalid payload (missing  if delete=true)"
    exit 1
  fi

  echo "Deleting the configuration $configuration..."
  delete_args=("delete" "-f" "$source/$configuration")
  logfile="/tmp/log"
  mkdir -p /tmp
  echo "Running command istioctl ${delete_args[@]} | tee $logfile"
  istioctl "${delete_args[@]}" | tee $logfile
}

if [ "$delete" = true ]; then
  istioctl_delete
  result="$(jq -n "{version:{configuration:\"$configuration\", deleted: \"true\"}, metadata: [{name: \"configuration\", value: \"$configuration\"}]}")"
  echo "$result" | jq -s add  >&3
else
  echo "Applying $configuration"
  istioctl_create

  echo "Deployed $configuration"
  result="$(jq -n "{version:{configuration:\"$configuration\"}, metadata: [{name: \"configuration\", value: \"$configuration\"}]}")"
  echo "$result" | jq -s add  >&3
fi